version: "3"

services:

  monitoring-app-backend:
    container_name: monitoring-app-backend
    build:
      context: ./monitoring-backend
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    networks:
      - monitoring-network
    environment:
      SPRING_ACTIVE_PROFILE: default


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: monitoring-app-db-password


  monitoring-app-frontend:
    container_name: monitoring-app-frontend
    build:
      context: ./monitoring-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge
